# coding: utf-8

"""
    SalesManagement WeChat API

    WeChat API  # noqa: E501

    OpenAPI spec version: 1.0.4
    Contact: sww19880825@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "wx-api"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="SalesManagement WeChat API",
    author_email="sww19880825@gmail.com",
    url="",
    keywords=["Swagger", "SalesManagement WeChat API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    WeChat API  # noqa: E501
    """
)
